version: '3.8'

services:
  backend:
    build:
      context: ./user-registration-back
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./user-registration-back:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./user-registration-front
      dockerfile: Dockerfile
    container_name: vue_app
    ports:
      - "8080:8080"

  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
